name: Decrypt, Build, Upload
on:
  push:
    branches: [ main ]
jobs:
  build-deploy-upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22'
    - name: Setup GPG
      run: |
        echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --import --batch --yes
        gpg --list-secret-keys --keyid-format LONG
    - name: Decrypt files
      env:
        GPG_KEY_ID: "316B2F8FD491F599"
      run: |
        ls values/*.yaml.gpg | xargs -I {} sh -c 'echo "${{ secrets.GPG_PASSPHRASE }}" | gpg --batch --yes --passphrase-fd 0 --pinentry-mode loopback --decrypt --recipient $GPG_KEY_ID "{}" > "$(dirname "{}")/$(basename "{}" .gpg)"'
    - name: Build
      run: make
    - name: Upload artifacts
      env:
        UPLOAD_TOKEN: ${{ secrets.UPLOAD_TOKEN }}
      run: |
        upload_file() {
          local file=$1
          echo "Uploading $file"
          curl -X POST -H "Authorization: Bearer $UPLOAD_TOKEN" -F "file=@$file" https://artifacts.monism.cc/upload
        }

        find artifacts/ -type f | while read file; do
          upload_file "$file"
        done
