name: Decrypt, Build, and Deploy

on:
  push:
    branches: [ main ]  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22'

    - name: Setup GPG
      run: |
        echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --import --batch --yes
        gpg --list-secret-keys --keyid-format LONG

    - name: Decrypt files
      env:
        GPG_KEY_ID: "316B2F8FD491F599"  
      run: |
        ls values/*.yaml.gpg | xargs -I {} sh -c 'echo "${{ secrets.GPG_PASSPHRASE }}" | gpg --batch --yes --passphrase-fd 0 --pinentry-mode loopback --decrypt --recipient $GPG_KEY_ID "{}" > "$(dirname "{}")/$(basename "{}" .gpg)"'

    - name: Build
      run: make

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./artifacts/
        destination_dir: ${{ secrets.DEPLOY_TOKEN }}  
        exclude_assets: '**/*'

    - name: Save secret URL
      env:
        URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ secrets.DEPLOY_TOKEN }}
      run: |
        echo $URL > secret_url.txt
        echo "Your secret URL is saved in the 'secret_url.txt' artifact"

    - name: Upload secret URL as artifact
      uses: actions/upload-artifact@v2
      with:
        name: secret-url
        path: secret_url.txt
